/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerAvaliacao;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author mathe
 */
public class Avaliacao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Avaliacao.class.getName());

    /**
     * Creates new form Avaliacao
     */
    public Avaliacao() {
        initComponents();
        agruparBotoes();
    }
    
    public Avaliacao(int idPedido) {
        initComponents();
        agruparBotoes();
        this.idPedidoParaAvaliar = idPedido;
        this.controller = new ControllerAvaliacao(this);
    }
    
    private void agruparBotoes() {
        ButtonGroup grupoAvaliacao = new ButtonGroup();
        grupoAvaliacao.add(rbZero);
        grupoAvaliacao.add(rbUm);
        grupoAvaliacao.add(rbDois);
        grupoAvaliacao.add(rbTres);
        grupoAvaliacao.add(rbQuatro);
        grupoAvaliacao.add(rbCinco);
    }

    public int getIdPedidoParaAvaliar() {
        return idPedidoParaAvaliar;
    }

    public void setIdPedidoParaAvaliar(int idPedidoParaAvaliar) {
        this.idPedidoParaAvaliar = idPedidoParaAvaliar;
    }

    public ControllerAvaliacao getController() {
        return controller;
    }

    public void setController(ControllerAvaliacao controller) {
        this.controller = controller;
    }

    public JButton getBtConfirmar() {
        return btConfirmar;
    }

    public void setBtConfirmar(JButton btConfirmar) {
        this.btConfirmar = btConfirmar;
    }

    public JLabel getLblAvalie() {
        return lblAvalie;
    }

    public void setLblAvalie(JLabel lblAvalie) {
        this.lblAvalie = lblAvalie;
    }

    public JRadioButton getRbCinco() {
        return rbCinco;
    }

    public void setRbCinco(JRadioButton rbCinco) {
        this.rbCinco = rbCinco;
    }

    public JRadioButton getRbDois() {
        return rbDois;
    }

    public void setRbDois(JRadioButton rbDois) {
        this.rbDois = rbDois;
    }

    public JRadioButton getRbQuatro() {
        return rbQuatro;
    }

    public void setRbQuatro(JRadioButton rbQuatro) {
        this.rbQuatro = rbQuatro;
    }

    public JRadioButton getRbTres() {
        return rbTres;
    }

    public void setRbTres(JRadioButton rbTres) {
        this.rbTres = rbTres;
    }

    public JRadioButton getRbUm() {
        return rbUm;
    }

    public void setRbUm(JRadioButton rbUm) {
        this.rbUm = rbUm;
    }

    public JRadioButton getRbZero() {
        return rbZero;
    }

    public void setRbZero(JRadioButton rbZero) {
        this.rbZero = rbZero;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas9 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();
        canvas3 = new java.awt.Canvas();
        canvas4 = new java.awt.Canvas();
        canvas5 = new java.awt.Canvas();
        rbUm = new javax.swing.JRadioButton();
        rbDois = new javax.swing.JRadioButton();
        rbTres = new javax.swing.JRadioButton();
        rbQuatro = new javax.swing.JRadioButton();
        rbCinco = new javax.swing.JRadioButton();
        rbZero = new javax.swing.JRadioButton();
        lblAvalie = new javax.swing.JLabel();
        btConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        canvas9.setBackground(new java.awt.Color(255, 255, 255));

        canvas2.setBackground(new java.awt.Color(102, 204, 255));

        canvas3.setBackground(new java.awt.Color(255, 255, 255));

        canvas4.setBackground(new java.awt.Color(102, 204, 255));

        canvas5.setBackground(new java.awt.Color(255, 255, 255));

        rbUm.setText("1 Estrela");
        rbUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUmActionPerformed(evt);
            }
        });

        rbDois.setText("2 Estrelas");
        rbDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDoisActionPerformed(evt);
            }
        });

        rbTres.setText("3 Estrelas");

        rbQuatro.setText("4 Estrelas");
        rbQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbQuatroActionPerformed(evt);
            }
        });

        rbCinco.setText("5 Estrelas");
        rbCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCincoActionPerformed(evt);
            }
        });

        rbZero.setText("0 Estrela");
        rbZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbZeroActionPerformed(evt);
            }
        });

        lblAvalie.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblAvalie.setText("Avalie o seu Pedido:");

        btConfirmar.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbTres)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rbDois, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbUm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbZero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(rbQuatro)
                                .addComponent(rbCinco)
                                .addComponent(lblAvalie, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(canvas9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(canvas3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(canvas4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(canvas5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvalie, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbZero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbDois)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbTres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbQuatro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbCinco)
                .addGap(12, 12, 12)
                .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbUmActionPerformed

    private void rbDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDoisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDoisActionPerformed

    private void rbQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbQuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbQuatroActionPerformed

    private void rbCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCincoActionPerformed

    private void rbZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbZeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbZeroActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        // TODO add your handling code here:
        if (controller != null) {
            controller.salvarAvaliacao(); // Chama o controller
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Avaliacao().setVisible(true));
//    }
    
    private int idPedidoParaAvaliar;
    private ControllerAvaliacao controller;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmar;
    private java.awt.Canvas canvas2;
    private java.awt.Canvas canvas3;
    private java.awt.Canvas canvas4;
    private java.awt.Canvas canvas5;
    private java.awt.Canvas canvas9;
    private javax.swing.JLabel lblAvalie;
    private javax.swing.JRadioButton rbCinco;
    private javax.swing.JRadioButton rbDois;
    private javax.swing.JRadioButton rbQuatro;
    private javax.swing.JRadioButton rbTres;
    private javax.swing.JRadioButton rbUm;
    private javax.swing.JRadioButton rbZero;
    // End of variables declaration//GEN-END:variables

}
