/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerBuscar;

/**
 *
 * @author uniemathrodrigues
 */
public class PaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInicial
     */
    public PaginaInicial() {
        initComponents();
        this.controllerBuscar = new ControllerBuscar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btLanches = new javax.swing.JButton();
        btPizza = new javax.swing.JButton();
        btBrasileira = new javax.swing.JButton();
        btSalgados = new javax.swing.JButton();
        btItaliana = new javax.swing.JButton();
        btJaponesa = new javax.swing.JButton();
        btBebidas = new javax.swing.JButton();
        btSobremesas = new javax.swing.JButton();
        btCarrinho = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();
        canvas3 = new java.awt.Canvas();
        canvas4 = new java.awt.Canvas();
        canvas5 = new java.awt.Canvas();
        canvas6 = new java.awt.Canvas();
        canvas7 = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setAlwaysOnTop(true);

        txtBuscar.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btBuscar.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btLanches.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btLanches.setText("Lanches");
        btLanches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLanchesActionPerformed(evt);
            }
        });

        btPizza.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btPizza.setText("Pizza");
        btPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPizzaActionPerformed(evt);
            }
        });

        btBrasileira.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btBrasileira.setText("Brasileira");
        btBrasileira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrasileiraActionPerformed(evt);
            }
        });

        btSalgados.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btSalgados.setText("Salgados");
        btSalgados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalgadosActionPerformed(evt);
            }
        });

        btItaliana.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btItaliana.setText("Italiana");
        btItaliana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btItalianaActionPerformed(evt);
            }
        });

        btJaponesa.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btJaponesa.setText("Japonesa");
        btJaponesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJaponesaActionPerformed(evt);
            }
        });

        btBebidas.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btBebidas.setText("Bebidas");
        btBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBebidasActionPerformed(evt);
            }
        });

        btSobremesas.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btSobremesas.setText("Sobremesas");
        btSobremesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSobremesasActionPerformed(evt);
            }
        });

        btCarrinho.setBackground(new java.awt.Color(102, 204, 255));
        btCarrinho.setFont(new java.awt.Font("Rockwell", 2, 14)); // NOI18N
        btCarrinho.setText("Carrinho");
        btCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarrinhoActionPerformed(evt);
            }
        });

        canvas1.setBackground(new java.awt.Color(255, 255, 255));

        canvas2.setBackground(new java.awt.Color(102, 204, 255));

        canvas3.setBackground(new java.awt.Color(255, 255, 255));

        canvas4.setBackground(new java.awt.Color(102, 204, 255));

        canvas5.setBackground(new java.awt.Color(255, 255, 255));

        canvas6.setBackground(new java.awt.Color(102, 204, 255));

        canvas7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSalgados, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btJaponesa, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSobremesas, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btItaliana, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLanches, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBrasileira, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(canvas7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCarrinho)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btCarrinho, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(canvas7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLanches, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBrasileira, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalgados, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btItaliana, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btJaponesa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSobremesas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        controllerBuscar.iniciarBuscaGlobal(this, txtBuscar.getText());
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btSobremesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSobremesasActionPerformed
        // TODO add your handling code here:
        controllerBuscar.iniciarBuscaCategoria(this, "Sobremesas");
    }//GEN-LAST:event_btSobremesasActionPerformed

    private void btPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPizzaActionPerformed
        // TODO add your handling code here:
        controllerBuscar.iniciarBuscaGlobal(this, "Pizza");
    }//GEN-LAST:event_btPizzaActionPerformed

    private void btCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarrinhoActionPerformed
        // TODO add your handling code here:
        Carrinho tela2 = new Carrinho();
        tela2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCarrinhoActionPerformed

    private void btLanchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLanchesActionPerformed
        // TODO add your handling code here:
        controllerBuscar.iniciarBuscaCategoria(this, "Lanches");
    }//GEN-LAST:event_btLanchesActionPerformed

    private void btSalgadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalgadosActionPerformed
        // TODO add your handling code here:
        controllerBuscar.iniciarBuscaCategoria(this, "Salgados");
    }//GEN-LAST:event_btSalgadosActionPerformed

    private void btBrasileiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBrasileiraActionPerformed
        // TODO add your handling code here:
        controllerBuscar.iniciarBuscaCategoria(this, "Brasileira");
    }//GEN-LAST:event_btBrasileiraActionPerformed

    private void btJaponesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJaponesaActionPerformed
        // TODO add your handling code here:
        controllerBuscar.iniciarBuscaCategoria(this, "Japonesa");
    }//GEN-LAST:event_btJaponesaActionPerformed

    private void btItalianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btItalianaActionPerformed
        // TODO add your handling code here:
        controllerBuscar.iniciarBuscaCategoria(this, "Italiana");
    }//GEN-LAST:event_btItalianaActionPerformed

    private void btBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBebidasActionPerformed
        // TODO add your handling code here:
        controllerBuscar.iniciarBuscaCategoria(this, "Bebidas");
    }//GEN-LAST:event_btBebidasActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PaginaInicial().setVisible(true);
//            }
//        });
//    }
    
    private final ControllerBuscar controllerBuscar;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBebidas;
    private javax.swing.JButton btBrasileira;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCarrinho;
    private javax.swing.JButton btItaliana;
    private javax.swing.JButton btJaponesa;
    private javax.swing.JButton btLanches;
    private javax.swing.JButton btPizza;
    private javax.swing.JButton btSalgados;
    private javax.swing.JButton btSobremesas;
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private java.awt.Canvas canvas3;
    private java.awt.Canvas canvas4;
    private java.awt.Canvas canvas5;
    private java.awt.Canvas canvas6;
    private java.awt.Canvas canvas7;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
